# Batch Method 
TJ Kim
8/1/20

Implement the following:

1) Shuffle users and jobs

2) Implement refresh rate based on mobility (3 for car, 6 for pedestrian, 0 for public)

3) Implement new batch method solver (we will move Seq-Greedy into this)

8/5/20

Testing with limited resources in a 3 server system to see if resource reservation works.

In [1]:
from IPython.core.debugger import set_trace

# Import Generic Classes
import numpy as np
import copy
import pickle
import random

# Import All Custom Classes
import os, sys
sys.path.append(os.path.pardir+"/classes")

from Server import *
from User import *
from Link import *
from Job import *
from Migration_Plans import *

from simulation_setting import *

# Import Solver Classes
from Optim_PlanGenerator import *
from SeqGreedy_PlanGenerator import *

### System Creation

Focus on shuffling + refresh rate.

In [5]:
users, servers, links, jobs, sim_param = simulation_setting()

In [6]:
SG_prob = SeqGreedy_PlanGenerator(users, servers, links, jobs, sim_param)
SG_plan = Migration_Plans(users,jobs,sim_param)
SG_plan.from_seq_greedy(SG_prob)

In [7]:
for key in SG_plan.mig_plan_dict[0]:
    print(key)
    print(SG_plan.mig_plan_dict[0][key])

time_slot
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
user_active_flag
[0. 0. 0. 1. 1. 1. 1. 0. 0. 0.]
user_voronoi
[4. 0. 4. 4. 1. 1. 3. 1. 1. 1.]
source_server
[-1. -1. -1.  4.  3.  1.  3. -1. -1. -1.]
dest_server
[-1. -1. -1.  3.  1.  3.  3. -1. -1. -1.]
mig_rate
[0. 0. 0. 1. 1. 1. 0. 0. 0. 0.]
mig_link_id
[0. 0. 0. 5. 0. 0. 0. 0. 0. 0.]
service_link_id
[-1. -1. -1. -1.  0. -1. -1. -1. -1. -1.]
service_thruput
[0.         0.         0.         0.         0.19559131 0.
 0.         0.         0.         0.        ]
latency
[ 0.          0.          0.          0.         27.20906315  0.
  0.          0.          0.          0.        ]


In [8]:
jobs[0].refresh_start_nodes

{3: (-1, -1), 4: (-1, 4), 5: (-1, 5), 6: (-1, 6)}

In [9]:
jobs[0].refresh_end_nodes

{3: (-1, 5), 4: (-1, 6), 5: (-1, 7), 6: (-1, 10)}