# Myopic Method 
TJ Kim
8/5/20

Implement the following:

1) test if plans are myopic only latency cost will be considered in a SG system.
2) The batch will be updated every timestep

In [1]:
from IPython.core.debugger import set_trace

# Import Generic Classes
import numpy as np
import copy
import pickle
import random

# Import All Custom Classes
import os, sys
sys.path.append(os.path.pardir+"/classes")

from Server import *
from User import *
from Link import *
from Job import *
from Migration_Plans import *

from simulation_setting import *

# Import Solver Classes
from Optim_PlanGenerator import *
from SeqGreedy_PlanGenerator import *
from Naive_PlanGenerator import *
from Myopic_PlanGenerator import *

In [2]:
users, servers, links, jobs, sim_param = simulation_setting()

In [3]:
M_prob = Myopic_PlanGenerator(users, servers, links, jobs, sim_param)
M_plan = Migration_Plans(users,jobs,sim_param)
M_plan.from_seq_greedy(M_prob)

In [4]:
for key in M_plan.mig_plan_dict[0]:
    print(key)
    print(M_plan.mig_plan_dict[0][key])

time_slot
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
user_active_flag
[1. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
user_voronoi
[2. 2. 2. 2. 2. 2. 2. 2. 0. 2.]
source_server
[ 2.  2.  0.  2.  2.  2.  2.  2. -1. -1.]
dest_server
[ 2.  0.  2.  2.  2.  2.  2.  2. -1. -1.]
mig_rate
[0. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
mig_link_id
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
service_link_id
[-1. -1.  0. -1. -1. -1. -1. -1. -1. -1.]
service_thruput
[0.         0.         0.09549895 0.         0.         0.
 0.         0.         0.         0.        ]
latency
[ 0.          0.         24.24234659  0.          0.          0.
  0.          0.          0.          0.        ]
